### ISSUE TITLE
[xxl-job]compose

### ISSUE THREAD

**Issue by Alice52** [Alice52/docker#31]
```yml
# https://blog.csdn.net/qq_39652397/article/details/123376681
version: '3.6'
services:
  xxl-job-admin-dev:
    image: registry.cn-shanghai.aliyuncs.com/alice52/xxl-job-admin:2.3.1
    container_name: xxl-job-admin-dev
    ports:
      - "8888:8080"
      - "8090:8090"
    environment:
      - spring.datasource.url=jdbc:mysql://192.168.191.122:3307/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
      - spring.datasource.username=root
      - spring.datasource.password=root
    restart: unless-stopped

```
