### ISSUE TITLE
[security] deploy

### ISSUE THREAD

**Issue by Alice52** [Alice52/docker#6]
##  vault

1. kv storage is memory: missing after re-start

    ![image](https://github.com/Alice52/docker/assets/42330329/e65240c9-3bdf-43da-a2da-8f3c435d1897)

3. integration with spring(must be cloud jar and must config in bootstrap.yml)
  - dependency
        ```xml
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-vault-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>
        ```
  - bootstrap.yml
      ```yml
      spring:
        cloud:
          vault:
            scheme: http
            host: xxx
            port: xxx
            authentication: token
            token: xxx
            kv:
              backend: kv/devl3
              application-name: antiabuse # kv/devl3/antiabuse  or kv/devl3/application
      ```

## reference

1. https://blog.csdn.net/sushiyi651/article/details/128407850
