### ISSUE TITLE
[docker] volumes

### ISSUE THREAD

**Issue by Alice52** [Alice52/docker#7]
1. type
  - 绝对路径挂载
  - 使用卷标的方式
2. diff
     - 如果宿主机目录不为空, 则使用现有文件进行挂载
     - 如果宿主机目录为空, 则将容器内文件复制到宿主机

     |   不同点   |                   volumns                   |           -v           |
     | :--------: | :-----------------------------------------: | :--------------------: |
     |  文件位置  |       /var/lib/docker/在 volumes/xxx        | 可以是宿主机的任意位置 |
     | 挂载点影响 | 第一次启动时会容器内目录数据会复制到 volume |   宿主机文件覆盖容器   |
     | 单文件映射 |                  只能目录                   |       目录+文件        |
     |    权限    |                 读写或只读                  |       读写或只读       |
     |   移植行   |              强 在 volumes/下               |   弱(宿主机绝对路径)   |

3. sample
```yml
version: '3.0'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
      - postgres:/var/log/postgresql

  redis:
    image: registry.cn-shanghai.aliyuncs.com/alice52/dev-standalone-redis:20200930.4e34876
    restart: 'always'
    container_name: dev-redis-standalone
    ports:
      - 6379:6379
    volumes:
      - /root/redis/standalone/data:/data

volumes:
    postgres:
```

## reference

1. https://blog.csdn.net/AV_woaijava/article/details/86685950
